name: Android CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Check Lint
        run: ./gradlew ktlintCheck

      - name: Unit Test
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

  ui-test:
    name: UI tests on Android (API level ${{ matrix.api-level }})
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 26, 28, 34 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: UI test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          arch: x86_64
          script: ./gradlew connectedCheck
